<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlantOps.Modules.Inventory.Contracts\PlantOps.Modules.Inventory.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PlantOps.Api.Tests" />
  </ItemGroup>

</Project>
