namespace PlantOps.Modules.WorkOrders.Contracts;

// The scheduled jobs of the WorkOrders module (ADR-0010). The module implements them; a host decides when to call
// them: the Azure Functions app from timer triggers, or the API's in-process BackgroundService in development.
// Both are idempotent, so a double run (two instances, a retried timer) is harmless.

/// <summary>Escalates open work orders that are past their deadline. Idempotent: each is escalated once.</summary>
public interface ISlaEscalationRunner
{
    /// <returns>How many work orders were escalated by this run.</returns>
    Task<int> RunAsync(CancellationToken cancellationToken);
}

/// <summary>Raises the work orders that preventive-maintenance schedules owe. Idempotent: never a duplicate per due date.</summary>
public interface IPreventiveMaintenanceRunner
{
    /// <returns>How many work orders were generated by this run.</returns>
    Task<int> RunAsync(CancellationToken cancellationToken);
}
