// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlantOps.Modules.Assets.Infrastructure;

#nullable disable

namespace PlantOps.Modules.Assets.Infrastructure.Migrations
{
    [DbContext(typeof(AssetsDbContext))]
    partial class AssetsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("assets")
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlantOps.BuildingBlocks.Infrastructure.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId", "OccurredAt")
                        .HasDatabaseName("IX_AuditEntries_AggregateId_OccurredAt");

                    b.ToTable("AuditEntries", "assets");
                });

            modelBuilder.Entity("PlantOps.Modules.Assets.Domain.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("CommissionedOn")
                        .HasColumnType("date");

                    b.Property<string>("Criticality")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DecommissionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("DecommissionedOn")
                        .HasColumnType("date");

                    b.Property<Guid>("LineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Station")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("_tag")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Tag");

                    b.HasKey("Id");

                    b.HasIndex("LineId")
                        .HasDatabaseName("IX_Assets_LineId");

                    b.HasIndex("_tag")
                        .IsUnique()
                        .HasDatabaseName("UX_Assets_Tag");

                    b.ToTable("Assets", "assets");
                });

            modelBuilder.Entity("PlantOps.Modules.Assets.Domain.ProductionLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductionLines_Code");

                    b.ToTable("ProductionLines", "assets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0197a5c0-0000-7000-8000-000000000001"),
                            Code = "SMT-1",
                            Name = "SMT Line 1"
                        },
                        new
                        {
                            Id = new Guid("0197a5c0-0000-7000-8000-000000000002"),
                            Code = "SMT-2",
                            Name = "SMT Line 2"
                        },
                        new
                        {
                            Id = new Guid("0197a5c0-0000-7000-8000-000000000003"),
                            Code = "FA-1",
                            Name = "Final Assembly 1"
                        },
                        new
                        {
                            Id = new Guid("0197a5c0-0000-7000-8000-000000000004"),
                            Code = "TEST-1",
                            Name = "Functional Test 1"
                        });
                });

            modelBuilder.Entity("PlantOps.Modules.Assets.Domain.Asset", b =>
                {
                    b.HasOne("PlantOps.Modules.Assets.Domain.ProductionLine", null)
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Assets_ProductionLines_LineId");
                });
#pragma warning restore 612, 618
        }
    }
}
